version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgress
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
  app: 
    image: testdocker
    container_name: testdocker
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env_deployment